### ISSUE TITLE
Automatically set vertices in format described in docstring of `Face::Face`

### ISSUE THREAD

**Issue by tanya-kta** [physarumAdv/minds_crawl#19]
First vertex of `Face::vertices` must be repeated in the end, but it's better if the user doesn't have to do that. `Face` constructor should get vertices and their number without repetition, then allocate memory for `Face::vertices` of size `n_of_vertices + 1`. `Face::n_of_vertices` should be equal `n_of_vertices`

**Comment by kolayne** [comment]
> `Face::n_of_vertices` should be equal `n_of_vertices`

I don't find this an obviously right decision. Probably it's more natural to have `n_of_vertices` to be equal to the number of elements in the `vertices` array :)
